/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-variant": "#e4e1ee",
        "tertiary-container": "#a44100",
        "on-primary-container": "#dad7ff",
        "primary": "#4f46e5",
        "primary-fixed": "#e2dfff",
        "primary-container": "#4f46e5",
        "surface-container-low": "#f5f2ff",
        "secondary-fixed": "#eaddff",
        "primary-fixed-dim": "#c3c0ff",
        "background": "#fcf8ff",
        "secondary-fixed-dim": "#d2bbff",
        "on-tertiary": "#ffffff",
        "on-secondary-container": "#fffbff",
        "surface-container-lowest": "#ffffff",
        "on-primary-fixed": "#0f0069",
        "surface-container-highest": "#e4e1ee",
        "on-secondary-fixed-variant": "#5a00c6",
        "surface-bright": "#fcf8ff",
        "secondary": "#712ae2",
        "on-surface-variant": "#464555",
        "surface-container-high": "#eae6f4",
        "on-tertiary-fixed": "#351000",
        "surface": "#fcf8ff",
        "surface-container": "#f0ecf9",
        "error": "#ba1a1a",
        "surface-dim": "#dcd8e5",
        "error-container": "#ffdad6",
        "outline-variant": "#c7c4d8",
        "on-surface": "#1b1b24",
        "inverse-surface": "#302f39",
        "on-tertiary-fixed-variant": "#7b2f00",
        "on-background": "#1b1b24",
        "secondary-container": "#8a4cfc",
        "tertiary-fixed-dim": "#ffb695",
        "outline": "#777587",
        "on-secondary-fixed": "#25005a",
        "on-error-container": "#93000a",
        "tertiary": "#7e3000",
        "on-primary-fixed-variant": "#3323cc",
        "tertiary-fixed": "#ffdbcc",
        "on-tertiary-container": "#ffd2be",
        "on-primary": "#ffffff",
        "on-secondary": "#ffffff",
        "surface-tint": "#4d44e3",
        "on-error": "#ffffff",
        "inverse-primary": "#c3c0ff",
        "inverse-on-surface": "#f3effc"
      },
      borderRadius: {
        "DEFAULT": "1rem",
        "lg": "2rem",
        "xl": "3rem",
        "full": "9999px"
      },
    },
  },
  plugins: [],
}
